export const state = {
  profile: {lthr:171, ltPaceSec:275, maxHR:191, vo2max:53, restHR:40},
  missingButtonsShownThisSession: false,
  bikeProfile: {ftp:'', thr:''},
  Z: undefined,
  WEEKS: undefined,
  currentWeek: 1,
  mode: 'outdoor',
  view: 'plan',
  appMode: 'run',
  recentSaveCache: {},
  cardModeOverride: {},
  expandedCards: {},
  toggleInProgress: false,
  renderToken: 0,
  stravaImportCache: {},
  stravaPendingCache: {},
  stravaRejectedCache: {},
  stravaSessionNameCache: {},
  stravaDayTagCache: {},
  sessionStructureCache: {},
  sessionTargetCache: {},
  stravaImportInFlight: {},
  weekPreviewCache: {},
  pendingImportData: null,
  latestVerdictCache: null,
  chatHistory: [],
  pendingSwapLink: null,
  freeWorkoutStravaCache: null,
  noteUidCounter: 0,
};
