export const state = {
  profile: {lthr:171, ltPaceSec:275, maxHR:191, vo2max:53, restHR:40},
  missingButtonsShownThisSession: false,
  bikeProfile: {ftp:'', thr:''},
  Z: undefined,
  layoffAdjustment: null,
  // What the current zone paces were actually derived from - {source, ltPaceSec, updatedAt,
  // raceVerified}, straight off getBestAvailableLTPace(). Kept in state (not re-fetched at
  // render time) because every render path that shows a pace target is synchronous, and the
  // runner needs to be able to see WHERE a pace came from to trust it.
  paceSource: null,
  missedSessionAdjustments: [],
  aheadOfScheduleSignals: [],
  likelySwapSuggestions: [],
  hardSessionProximityFlags: [],
  WEEKS: undefined,
  goalConfig: undefined,
  pendingPlanOverride: {},
  pendingGoalEdit: null,
  pendingDeleteGoalId: null,
  currentWeek: 1,
  mode: 'outdoor',
  view: 'plan',
  appMode: 'run',
  recentSaveCache: {},
  cardModeOverride: {},
  cardAltOverride: {},
  cardTrailOverride: {},
  expandedCards: {},
  toggleInProgress: false,
  renderToken: 0,
  stravaImportCache: {},
  stravaCandidatesCache: {},
  stravaSessionNameCache: {},
  stravaDayTagCache: {},
  sessionStructureCache: {},
  sessionTargetCache: {},
  sessionTypeCache: {},
  stravaImportInFlight: {},
  weekPreviewCache: {},
  weekPreviewInFlight: {},
  pendingImportData: null,
  latestVerdictCache: null,
  chatHistory: [],
  pendingSwapLink: null,
  pendingRetryLink: null,
  freeWorkoutStravaCache: null,
  noteUidCounter: 0,
};
